apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nano-example
  name: backend
  namespace: nano-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nano-example
  template:
    metadata:
      labels:
        app: nano-example
        server: backend
    spec:
      containers:
        - image: quay.io/felipejfc/nano-example-sv:v1
          command:
            - /server
            - -type
            - game
            - -frontend=false
          env:
            - name: NANO_CLUSTER_RPC_CLIENT_NATS_CONNECT
              value: nats://nats-cluster-1.nats-io.svc.cluster.local:4222
            - name: NANO_CLUSTER_RPC_SERVER_NATS_CONNECT
              value: nats://nats-cluster-1.nats-io.svc.cluster.local:4222
            - name: NANO_CLUSTER_SD_ETCD_ENDPOINTS
              value: etcd-cluster-1.etcd.svc.cluster.local:2379
            - name: NANO_HEARTBEAT_INTERVAL
              value: 10s
          name: backend
          resources:
            limits:
              cpu: 1000m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 200Mi
