apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nano-example
  name: frontend
  namespace: nano-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nano-example
  template:
    metadata:
      labels:
        app: nano-example
        server: frontend
    spec:
      containers:
        - image: quay.io/felipejfc/nano-example-sv:v1
          command:
            - /server
            - -type
            - connector
            - -frontend=true
          env:
            - name: NANO_CLUSTER_RPC_CLIENT_NATS_CONNECT
              value: nats://nats-cluster-1.nats-io.svc.cluster.local:4222
            - name: NANO_CLUSTER_RPC_SERVER_NATS_CONNECT
              value: nats://nats-cluster-1.nats-io.svc.cluster.local:4222
            - name: NANO_CLUSTER_SD_ETCD_ENDPOINTS
              value: etcd-cluster-1.etcd.svc.cluster.local:2379
            - name: NANO_HEARTBEAT_INTERVAL
              value: 10s
          name: frontend
          resources:
            limits:
              cpu: 1000m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nano-example
  name: frontend
  namespace: nano-example
spec:
  ports:
    - name: tcp
      port: 32222
      protocol: TCP
      targetPort: 32222
  selector:
    app: nano-example
    server: frontend
  type: LoadBalancer
